### ISSUE TITLE
Some warnings have a non-valid link to the code

### ISSUE THREAD

**Issue by messers2** [JacobDomagala/CompileResult#26]
![2023-09-04 16_24_14-Draft_ Plat 1439 show warnings · Hillrom-Enterprise_platfORm_ao@3082f11 - Vivald](https://github.com/JacobDomagala/CompileResult/assets/135332507/d78d7eac-efb7-4381-8fd8-279e37979866)

The referenced sources still exist, but the reference seems to be invalid. Any ideas? 
The PR-comment was produced during a job run that runs in parallel with more jobs during an PR-update

**Comment by JacobDomagala** [comment]
Is that file a part of git repository or is it being generated during build process? I'm asking because I can see `//build/` in file path. 
Do you build it inside a custom docker or as an action step? 

Running in a matrix strategy shouldn't be a problem.

**Comment by messers2** [comment]
mmh, you're right, the file is from a fetch_content command and subsequently copied to the build directory. I'll have to check on this, but I think this happens also for other files (files located in the source). For this kind of files I'll have to filter out these warning lines. So I guess the /blob/-directory is not persistent as long as the PR is open but only as long as the build is running

**Comment by messers2** [comment]
For future reference: It really only affected sources that were part of external dependencies, so I could filter them out straight forward by treating the compiler output file like this (where the /_deps/ directory provides the means to discriminate the dependencies:
```shell
 sed -i '/.*\/_deps\/.*\swarning:/d' compiler_output/${{ matrix.configs }}.txt
```
